### ISSUE TITLE
mbed-os imported by cli

### ISSUE THREAD

**Issue by artokin** [ARMmbed/mbed-client-cli#81]
mbed-client-cli imports version of mbed-os in example folder.

This will cause that application that is already importing version of Mbed OS will also import another copy of Mbed OS from mbed-client-cli/examples/mbed-os-xxx. 

### Description
- Type: Bug

**Comment by jupe** [comment]
this causes because of mbed-cli does not respect .mbedignore when importing libraries (https://github.com/ARMmbed/mbed-cli/issues/407) . We can create workaround by removin .lib files from example folder and tuning Ci to generate it when compiling example. Hopefully we get original issue fixed asap..
